### PR TITLE
pushtx+rescan: stop rebroadcast on tx confirm

### LINKED ISSUE #206: Neutrino seems to be expecting a MsgReject when broadcasting a tx, but btcd does not reply to the INV
In order to decide when to stop rebroadcasting, [Broadcaster is expecting to see a MsgReject](https://github.com/lightninglabs/neutrino/blob/38bf97e348a3d89c8f473209abf811c64074e5b5/pushtx/broadcaster.go#L236). But I see that broadcaster calls cfg.Broadcast which ends in [ChainService.sendTransaction()](https://github.com/lightninglabs/neutrino/blob/39da434881572f823bee55994995a9e46fc985e9/query.go#L1118) and this is sending an INV message. On the btcd side, INV messages which are already known *in any way* are quietly ignored, as you can see in [SyncManager.handleInvMessage()](https://github.com/btcsuite/btcd/blob/96897255fd17525dd12426345d279533780bc4e1/netsync/manager.go#L1118) so unless I am mistaken, this idea of rebroadcasting until someone rejects as duplicate is not just non-ideal, it actually doesn't work in the normal case (unless bitcoind works differently, in which a case could be made that this is btcd's bug).

### PR DESCRIPTION
**Pull request by ellemouton**
This PR allows rescan to notify the `ChainServices` `broadcaster` that a relevant transaction is confirmed.

Fixes #206  using the approach mentioned [here](https://github.com/lightninglabs/neutrino/issues/206#issuecomment-887919095)

**Testing the PR**
- _To see the bug_: An easy way to test this just by running an lnd itest that creates some channels and then observing the logs. So currently, if you run `$ make itest backend=neutrino icase=....` (choose a test that creates a lot of channels) and then look at the logs: `[DBG] BTCN: Re-broadcasting %d transactions`  will show that the number of txs being rebroadcasted just keeps increasing. 
- _To see the fix:_ now in lnd go.mod, add: `replace github.com/lightninglabs/neutrino => github.com/ellemouton/neutrino v0.11.1-0.20210921111409-eb86c412013d` and re-run the same itest. You will see that the number of txs being rebroadcast no longer increases when a tx is confirmed.

Fixes https://github.com/lightninglabs/neutrino/issues/206

### CODE REVIEW

File: rescan.go [hunk 1]
```diff
@@ -1007,6 +1007,11 @@ func extractBlockMatches(chain ChainSource, ro *rescanOptions,
 
 		if relevant {
 			relevantTxs = append(relevantTxs, tx)
+
+			cs, ok := chain.(*RescanChainSource)
```
Comment (arshbot) [inline rescan.go:1011]: nit: `cs` for `chainsource`? Although it doesn't seem enforced in this codebase, longer names could improve readability :)

**Review by arshbot — CHANGES_REQUESTED** [review]
Love the minimal diff! Great commit structure. Left a tiny nit but this is fairly straightforward.

File: rescan.go (hunk 1 above)
Comment (ellemouton) [reply rescan.go]: sure, updated 👍

**Review by Roasbeef — APPROVED** [review]
Very straightforward fix! 

LGTM 🧩

Will need a PR now to the `lnd` repo to update the go.mod there

**Comment by Roasbeef** [comment]
Also re which "option" this PR took: with the added method those that use the library outside of the lnd+btcwallet interaction can use that method to clean up the main state.

**Comment by ellemouton** [comment]
> added method those that use the library outside of the lnd+btcwallet interaction can use that method to clean up the main state.

Hmmm but the method is not exposed to them if they just have ChainServices. Should I add a method to ChainServices to expose this method on Broadcaster?

**Comment by ellemouton** [comment]
> Will need a PR now to the lnd repo to update the go.mod there

Is it fine to point to the latest commit or shall we push a new tag to neutrino?

**Review by Kenme1234 — COMMENTED** [review]
Fb
